// find-the-difference - Given two strings s and t which consist of only lowercase
// letters.
// String t is generated by random shuffling string s and then add
// one more letter at a random position.
// Find the letter that was added in t
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output: e
//
// Explanation: 'e' is the letter that was added.
//
// https://leetcode.com/problems/find-the-difference
#include "solution.h"

using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        int in_s[26] = {0}, in_t[26] = {0};
        for (size_t i = 0; i < s.size(); i++) {
            ++in_s[s[i] - 'a'];
            ++in_t[t[i] - 'a'];
        }

        ++in_t[t.back() - 'a'];
        for (size_t i = 0; i < 26; i++) {
            if (in_s[i] != in_t[i]) {
                return i + 'a';
            }
        }

        return '\0';
    }

    char findTheDifference2(string s, string t) {
        int x = 0;
        for (size_t i = 0; i < s.size(); i++) {
            x ^= s[i];
            x ^= t[i];
        }

        return x ^ t.back();
    }
};

int main()
{
    cout << Solution().findTheDifference2("abcd", "bdcae") << endl;
}
